version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgresuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgrespassword}
      POSTGRES_DB: ${DB_NAME:-sampledb}
  mysql:
    image: mysql
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      MYSQL_USER: ${DB_USERNAME:-mysqluser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-mysqlpassword}
      MYSQL_DATABASE: ${DB_NAME:-sampledb}
      MYSQL_ROOT_PASSWORD: mysqlpassword
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - ${DB_PORT:-27017}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME:-mongouser}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-mongopassword}
      MONGO_INITDB_DATABASE: ${DB_NAME:-sampledb}
