version: '3.9'
services:
  api:
    container_name: express-api
    build:
      context: .
      target: prod
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      NODE_ENV: production
