version: '3.9'
services:
  api:
    extends:
      file: docker-compose.prod.yml
      service: api
    build:
      target: dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      NODE_ENV: development
volumes:
  node_modules:
